name: gunsel
description: Project by Günsel Lines.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  url_launcher: ^5.0.3
  http: ^0.12.0
  shared_preferences: ^0.5.3+4
  flutter_facebook_login: ^1.2.0
  flutter_typeahead: ^1.6.1
  carousel_pro: ^1.0.0
  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "images/icon.jpg"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.a
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/calendar_icon_1.png
    - assets/swapping_icon.png
    - assets/splash_image.jpg
    - assets/loginBG.jpg
    - assets/BG.jpg
    - assets/drawer_log_out.jpg
    - assets/drawer_log_in.jpg
    - assets/user.png
    - assets/czech.png
    - assets/ukraine.png
    - assets/poland.png
    - assets/google.png
    - assets/facebook.png
    - assets/profileBG.jpg
    - assets/russia.png
    - assets/visaverify.png
    - assets/mastercard.png
    - assets/person.png
    - assets/person-image.png
    - assets/white.jpg
    - assets/profileicon.png
    - assets/profileholder.png
    - assets/profile_edit.png
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/4.png
    - assets/bus.png
    - assets/aboutcompany.png
    - assets/money.png
    - assets/newIcon.png
    - assets/purchasedticket.png
    - assets/ticketw729h201.png
    - assets/cancelIcon.png
    - assets/profile_icon.png
    - assets/languageIcon.png
    - assets/phone.png
    - assets/map_icon.png
    - assets/about-Image.jpg
    - assets/log_out_icon.png
    - assets/unchecked.png
    - assets/logo_light.png
    - assets/ticket.png
    - assets/bigticket.png
    - assets/selectseatscreen.png
    - assets/backArrow_2.png
    - assets/menu_icon_2.png
    - assets/password_icon.png
    - assets/england.png
    - assets/payment_thumb.png
    - images/front.webp
    - images/seat.png
    - images/news1.webp
    - images/green_seat.png
    - assets/gradient.png
    - images/red_seat.png
    - assets/checked.png
    - assets/menu_background.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica_CY.ttf
        - asset: fonts/Helvetica_CY_Bold.ttf
          weight: 700
    - family: MyriadPro
      fonts:
        - asset: fonts/MyriadPro_Regular.otf
    - family: SFProText
      fonts:
        - asset: fonts/SFProText_Light.ttf
          weight: 300
        - asset: fonts/SFProText_Heavy.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
